# Generated by Django 4.0.2 on 2022-03-11 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insomnia_keeper_main', '0002_adminsettings_fee_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
    ]
