# Generated by Django 4.0.3 on 2022-03-11 22:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insomnia_keeper_main', '0003_remove_profile_name_remove_profile_surname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Global',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Контактный номер телефона')),
                ('whatsapp_number', models.PositiveBigIntegerField(blank=True, help_text='В междунарожном формате, подробнее <a href="https://faq.whatsapp.com/general/chats/how-to-use-click-to-chat" target="_blank">тут</a>', null=True, verbose_name='WhatsApp номер')),
                ('instagram_username', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram username')),
                ('telegram_link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telegram link')),
                ('facebook_username', models.CharField(blank=True, help_text='https://facebook.com/<ваш username>/', max_length=50, null=True, verbose_name='Facebook username')),
                ('usd_rub_exchange_rate', models.DecimalField(decimal_places=50, default=120, max_digits=100, verbose_name='1 USD -> x RUB курс')),
                ('usd_eur_exchange_rate', models.DecimalField(decimal_places=50, default=Decimal('0.91400000000000003463895836830488406121730804443359375'), max_digits=100, verbose_name='1 USD -> x EUR курс')),
                ('btc_usd_exchange_rate', models.DecimalField(decimal_places=50, default=Decimal('38902'), max_digits=100, verbose_name='1 BTC -> x USD курс')),
                ('eth_usd_exchange_rate', models.DecimalField(decimal_places=50, default=Decimal('2577'), max_digits=100, verbose_name='1 ETH -> x USD курс')),
                ('ton_usd_exchange_rate', models.DecimalField(decimal_places=50, default=Decimal('1.8600000000000000976996261670137755572795867919921875'), max_digits=100, verbose_name='1 TON -> x USD курс')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Пресет настройки',
                'verbose_name_plural': 'Глобальные настройки',
            },
        ),
        migrations.DeleteModel(
            name='Fixed',
        ),
        migrations.RemoveField(
            model_name='error',
            name='browser_name',
        ),
        migrations.RemoveField(
            model_name='error',
            name='full_version',
        ),
        migrations.RemoveField(
            model_name='error',
            name='major_version',
        ),
        migrations.RemoveField(
            model_name='error',
            name='navigator_app_name',
        ),
        migrations.RemoveField(
            model_name='error',
            name='navigator_user_agent',
        ),
        migrations.RemoveField(
            model_name='error',
            name='os_name',
        ),
        migrations.AddField(
            model_name='error',
            name='info',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Информация'),
        ),
    ]
