# Generated by Django 4.0.3 on 2022-03-12 02:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insomnia_keeper_main', '0004_global_delete_fixed_remove_error_browser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='sendgrid_api_key',
            field=models.CharField(default='', max_length=1000, verbose_name='SendGrid API key'),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='sendgrid_sender_email',
            field=models.CharField(default='', max_length=1000, verbose_name='SendGrid Sender Email'),
        ),
        migrations.AlterField(
            model_name='global',
            name='btc_usd_exchange_rate',
            field=models.DecimalField(decimal_places=100, default=Decimal('38902'), max_digits=200, verbose_name='1 BTC -> x USD курс'),
        ),
        migrations.AlterField(
            model_name='global',
            name='eth_usd_exchange_rate',
            field=models.DecimalField(decimal_places=100, default=Decimal('2577'), max_digits=200, verbose_name='1 ETH -> x USD курс'),
        ),
        migrations.AlterField(
            model_name='global',
            name='ton_usd_exchange_rate',
            field=models.DecimalField(decimal_places=100, default=Decimal('1.8600000000000000976996261670137755572795867919921875'), max_digits=200, verbose_name='1 TON -> x USD курс'),
        ),
        migrations.AlterField(
            model_name='global',
            name='usd_eur_exchange_rate',
            field=models.DecimalField(decimal_places=100, default=Decimal('0.91400000000000003463895836830488406121730804443359375'), max_digits=200, verbose_name='1 USD -> x EUR курс'),
        ),
        migrations.AlterField(
            model_name='global',
            name='usd_rub_exchange_rate',
            field=models.DecimalField(decimal_places=100, default=120, max_digits=200, verbose_name='1 USD -> x RUB курс'),
        ),
        migrations.AlterField(
            model_name='keeper',
            name='btc_wallet_balance',
            field=models.DecimalField(decimal_places=100, default=0, max_digits=200, verbose_name='Bitcoin баланс'),
        ),
        migrations.AlterField(
            model_name='keeper',
            name='eth_wallet_balance',
            field=models.DecimalField(decimal_places=100, default=0, max_digits=200, verbose_name='Etherium баланс'),
        ),
        migrations.AlterField(
            model_name='keeper',
            name='ton_wallet_balance',
            field=models.DecimalField(decimal_places=100, default=0, max_digits=200, verbose_name='Toncoin баланс'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=100, default=0, max_digits=200, verbose_name='Количество'),
        ),
    ]
